---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ucore
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/ucore
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    snippets:
      - "dnf5 copr enable @caddy/caddy -y"

  - type: dnf
    install:
      packages:
        - repo: copr:copr.fedorainfracloud.org:group_caddy:caddy
          packages:
            - caddy # force installing caddy from copr
        - wget
        - htop

  - type: script
    scripts:
      - install-vpn.sh
    snippets:
      - "dnf5 copr disable @caddy/caddy -y"

  - type: systemd
    system:
      enabled:
        - x-ui

  - type: signing
